/**
 * Here stores global constants.
 */

export const METADATA_KEY_CLASS_IS_RENDERED: string = 'METADATA_KEY_CLASS_IS_RENDERED'
export const METADATA_KEY_METHOD_ARRAY: string = 'METADATA_KEY_METHOD_ARRAY'
export const METADATA_KEY_ACCESSOR_ARRAY: string = 'METADATA_KEY_ACCESSOR_ARRAY'
export const METADATA_KEY_PROPERTY_ARRAY: string = 'METADATA_KEY_PROPERTY_ARRAY'
export const METADATA_KEY_PARAMETER_ARRAY: string = 'METADATA_KEY_PARAMETER_ARRAY'
